cart/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('', views.index, name="index"),
    path('addtocartget', views.addtocartget, name="addtocart"),
    path('deletecartget', views.deletecartget, name="deletecartget"),
    path('docartitem', views.docartitem, name="docartitem")
]

e_commerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('product/', include('product.urls')),
    path('order/', include('order.urls')),
    path('cart/', include('cart.urls')),
    path('feedback/', include('feedback.urls')),

]

order/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('', views.index, name="index"),
    path('manageshipment', views.manageshipment, name="manageshipment"),
    path('deleteShipment/<int:id>', views.deleteShip, name ='deleteShipment'),
    path('addShipment/', views.addShipment, name ='addShipment'),
    path('managepayment', views.managepayment, name="managepayment"),
    path('deletePayment/<int:id>', views.deletePay, name ='deletePayment'),
    path('addPayment/', views.addPayment, name='addPayment'),
    path('manageorder', views.manageorder, name="manageorder"),
    path('manageorder/orderchecked', views.setorderchecked, name='setorderchecked'),
    path('manageorder/ordercanceled', views.setordercancel, name='setordercancel'),
    path('checkout', views.checkout, name="checkout"),
    path('confirm', views.confirm, name="confirm")
]

cart/models.py
from django.db import models
from user.models import User
from product.models import Item


class Cart(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    userid = models.ForeignKey(User, models.DO_NOTHING, db_column='UserID', blank=True,
                               null=True)  # Field name made lowercase.
    state = models.IntegerField(db_column='State', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        db_table = 'cart'

class CartItem(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    cartid = models.ForeignKey(Cart, models.DO_NOTHING, db_column='CartID')  # Field name made lowercase.
    itemid = models.ForeignKey(Item, models.DO_NOTHING, db_column='ItemID')  # Field name made lowercase.
    quantity = models.IntegerField(db_column='Quantity', blank=True, null=True)  # Field name made lowercase.
    cost = models.FloatField(db_column='Cost', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        db_table = 'cart_item'
        # unique_together = (('cartid', 'itemid'),)

feedback/models.py
from django.db import models
from user.models import User, Customer
from cart.models import CartItem

# Create your models here.
class Feedback(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    customeruserid = models.ForeignKey(Customer, models.DO_NOTHING, db_column='CustomerUserID')  # Field name made lowercase.
    cartitemid = models.ForeignKey(CartItem, models.DO_NOTHING, db_column='CartItemID')  # Field name made lowercase.
    content = models.CharField(db_column='Content', max_length=255, blank=True, null=True)  # Field name made lowercase.
    star = models.IntegerField(db_column='Star', blank=True, null=True)  # Field name made lowercase.
    time = models.DateField(db_column='Time', blank=True, null=True)  # Field name made lowercase.
    status = models.CharField(db_column='Status', max_length=255, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        db_table = 'feedback'

order/models.py
from django.db import models
from cart.models import Cart, CartItem
from user.models import User, Customer


class Order(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    customeruserid = models.ForeignKey(Customer, models.DO_NOTHING,
                                       db_column='CustomerUserID')  # Field name made lowercase.
    paymentid = models.ForeignKey('Payment', models.DO_NOTHING, db_column='PaymentID')  # Field name made lowercase.
    cartid = models.ForeignKey(Cart, models.DO_NOTHING, db_column='CartID')  # Field name made lowercase.
    shipmentid = models.ForeignKey('Shipment', models.DO_NOTHING, db_column='ShipmentID')  # Field name made lowercase.
    num = models.IntegerField(db_column='Num', blank=True, null=True)  # Field name made lowercase.
    time = models.DateField(db_column='Time', blank=True, null=True)  # Field name made lowercase.
    state = models.CharField(db_column='State', max_length=255, blank=True, null=True)  # Field name made lowercase.
    address = models.CharField(db_column='Address', max_length=255, blank=True, null=True)

    class Meta:
        db_table = 'order'


class Payment(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    type = models.CharField(db_column='Type', max_length=255, blank=True, null=True)  # Field name made lowercase.
    amount = models.FloatField(db_column='Amount', blank=True, null=True)  # Field name made lowercase.
    discountrate = models.FloatField(db_column='DiscountRate', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        db_table = 'payment'


class Shipment(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    address = models.CharField(db_column='Address', max_length=255, blank=True, null=True)  # Field name made lowercase.
    price = models.FloatField(db_column='Price', blank=True, null=True)  # Field name made lowercase.
    type = models.CharField(db_column='Type', max_length=255, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        db_table = 'shipment'

order/views.py
from datetime import datetime

from django.shortcuts import render, redirect

from feedback.models import Feedback
from user.models import User
from order.models import Payment,Shipment, Order
from django.db import transaction
from cart.models import CartItem,Cart
from product.models import Item, Product, Supplier, Category, Comment
from user.models import User, Customer, Fullname, Address
# Create your views here.

def index(request):
    user_id = request.session["user_id"]
    user = User.objects.get(id=user_id)
    cus = Customer.objects.get(userid=user)
    orders = Order.objects.filter(customeruserid=cus)
    cartitem = None
    if request.POST.get("process", "") == "feedback":
        content = request.POST.get("content", "")
        rate = request.POST.get("rate", "")
        cartitemid = request.POST.get("cartitemid", "")
        cartitemp = CartItem.objects.get(id=cartitemid)
        try:
            with transaction.atomic():
                Feedback.objects.create(
                    content=content,
                    star=rate,
                    time=datetime.now().strftime("%Y-%m-%d"),
                    status="Success",
                    cartitemid=cartitemp,
                    customeruserid=cus
                )
            return redirect("/order")
        except Exception as e:
            print(e)
            print("delete faild")
    else:
        cartitemid = request.GET.get("feedback", "")

        if cartitemid != "":
            cartitem = CartItem.objects.get(id=cartitemid)

    return render(request, 'orders.html', {'orders': orders, 'cartitem': cartitem})

def manageshipment(request):

    addmodel = request.GET.get('add')
    if "user_id" in request.session.keys():
        user_id = request.session["user_id"]
        user = User.objects.get(id=user_id)
        payment = Payment.objects.all()
        shipment = Shipment.objects.all()
        print("user_id", user)

    else:
        user = None
    return render(request,'manageshipment.html', {'payment': payment,
                                                 'user': user, 'shipment': shipment, 'addmodel': addmodel})
def deleteShip(request, id):
    try:
        with transaction.atomic():
            Shipment.objects.filter(id=id).delete()

    except Exception as e:
        print(e)
        print("delete faild")

    return redirect("/order/manageshipment")

def addShipment(request):
    if request.method == "POST":
        shipment_type = request.POST.get("shipment_type")
        shipment_price = request.POST.get("shipment_price")

        print(shipment_type, shipment_price)
        try:
            with transaction.atomic():
                shipment = Shipment.objects.create(type=shipment_type,
                                       price=shipment_price,
                                       )
                print(shipment)

        except Exception as e:

            print(e)
            print("insert faild")

        return redirect("/order/manageshipment")
    else:
        return redirect("/order/manageshipment")

# view payment
def managepayment(request):

    addmodel = request.GET.get('add')
    if "user_id" in request.session.keys():
        user_id = request.session["user_id"]
        user = User.objects.get(id=user_id)
        payment = Payment.objects.all()
        shipment = Shipment.objects.all()
        print("user_id", user)

    else:
        user = None
    return render(request,'managepayment.html', {'payment': payment,
                                                 'user': user, 'shipment': shipment, 'addmodel': addmodel})
def deletePay(request, id):
    try:
        with transaction.atomic():
            Payment.objects.filter(id=id).delete()

    except Exception as e:
        print(e)
        print("delete faild")

    return redirect("/order/managepayment")

def addPayment(request):
    if request.method == "POST":
        payment_type = request.POST.get("payment_type")
        payment_discountrate = request.POST.get("payment_discountrate")

        print(payment_type, payment_discountrate)
        try:
            with transaction.atomic():
                payment = Payment.objects.create(type=payment_type,
                                       discountrate=payment_discountrate,
                                       )
                print(payment)

        except Exception as e:

            print(e)
            print("insert faild")

        return redirect("/order/managepayment")
    else:
        return redirect("/order/managepayment")

def manageorder(request): # get toan bo order
    orders = []
    for o in Order.objects.all():
        orders.append(o)
    orderid = request.GET.get('orderid')
    print(orderid)
    order = None
    if orderid is not None:
        order = Order.objects.get(id = orderid)
        # print(order.userid.fullname_set.all()[0].first)

    return render(request, 'manageorder.html', {'orders': orders, 'order': order})

def goorderdetail(request, id): # get order detail
    orderdetail = Order.objects.get(ID=id)
    cart = Cart.objects.get(ID=order.cartID)
    cartitems = []
    print(orderdetail)
    items = []
    for ci in CartItem.objects.filter(CartID=cart.ID):
        cartitems.append(ci)
        for i in Item.objects.filter(ID=ci.ItemID):
            items.append(i)
    return render(request, 'manageorder.html', { 'orderdetail': orderdetail})

def setorderchecked(request):
    if request.method == "POST":
        orderid = request.POST.get('orderid')
        print('Orderid', orderid)
        Order.objects.filter(id=orderid).update(state='Confirmed')
        return redirect('/order/manageorder')
    else:
        return redirect('/order/manageorder')


def setordercancel(request):
    if request.method == "POST":
        orderid = request.POST.get('orderid')
        print('Orderid', orderid)
        Order.objects.filter(id=orderid).update(state='Canceled')
        return redirect('/order/manageorder')
    else:
        return redirect('/order/manageorder')


def checkout(request):

    payments = Payment.objects.all()
    shipments = Shipment.objects.all()

    return render(request, 'checkout.html', {'payments': payments, 'shipments': shipments})

def confirm(request):

    homenumber = request.GET.get("homenumber")
    street = request.GET.get("street")
    district = request.GET.get("district")
    city = request.GET.get("city")
    country = request.GET.get("country")
    fullname = request.GET.get("fullname")
    phone = request.GET.get("phone")
    shipmentid = request.GET.get("shipment")
    paymentid = request.GET.get("payment")
    shipment = Shipment.objects.get(id=shipmentid)
    payment = Payment.objects.get(id=paymentid)

    user_id = request.session['user_id']
    print('user_id', user_id)
    user = User.objects.get(id=user_id)
    if request.POST.get("proceed") == "confirm":
        cartid = request.POST.get("cartid")
        cart = Cart.objects.get(id=cartid)
    else:
        cart = Cart.objects.filter(state=0, userid=user).first()
    total = 0
    if cart is not None:
        cartitems = CartItem.objects.filter(cartid=cart)
        for cartitem in cartitems:
            total += cartitem.cost * cartitem.quantity
    else:
        cartitems = None

    fulltoal = (total+shipment.price)*(1-payment.discountrate)
    order = None
    if request.POST.get("proceed") == "confirm":
        order = Order.objects.filter(customeruserid=user_id, cartid=cart).first()
        if order is None:
            try:
                with transaction.atomic():
                    cus = Customer.objects.get(userid=user_id)
                    order = Order.objects.create(
                        customeruserid=cus,
                        cartid=cart,
                        paymentid=payment,
                        shipmentid=shipment,
                        num=fulltoal,
                        time=datetime.now().strftime("%Y-%m-%d"),
                        state="Pending",
                        address="{} {}, {}, {}, {}".format(homenumber, street, district, city, country)
                    )
                    cart = Cart.objects.filter(id=cart.id).update(state=1)
            except Exception as e:
                print(e)
                print("insert faild")


    print("order", order)

    return render(request, 'confirmview.html', {
        'homenumber': homenumber,
        'street': street,
        'district': district,
        'city': city,
        'country': country,
        'shipment': shipment,
        'payment': payment,
        'cartitems': cartitems,
        'cart': cart,
        'total': total,
        'user': user,
        'phone': phone,
        'fullname': fullname,
        'order': order
    })

order/templates/checkout.html
{% include "header.html" %}
{% load static %}
{% load mathfilters %}
    <div class="single-product-area">
            <h2 style="text-align: center; color: #5a88ca; font-weight:800;">CHECKOUT</h2>
            <br>
        <div class="zigzag-bottom"></div>
        <div class="container">
            <form method="get" action="/order/confirm">
                                {% csrf_token %}
                <div class="row">
                    <div class="col-md-6">

                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>HomeNumber</label>
                                    <input type="text" name="homenumber" class="form-control">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Street</label>
                                    <input type="text" name="street" class="form-control">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>District</label>
                                    <input type="text" name="district" class="form-control">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>City</label>
                                    <input type="text" name="city" class="form-control">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Country</label>
                                    <input type="text" name="country" class="form-control">
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label>Shipment</label>
                            <select name="shipment" class="form-control">
                                {% for shipment in shipments %}
                                <option value="{{ shipment.id }}">{{ shipment.type }} - {{ shipment.price }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Fullname</label>
                            <input class="form-control" name="fullname">
                        </div>
                        <div class="form-group">
                            <label>Phone</label>
                            <input class="form-control" name="phone">
                        </div>
                        <div class="form-group">
                            <label>Payment</label>
                            <select name="payment" class="form-control">
                                {% for payment in payments %}
                                <option value="{{ payment.id }}">{{ payment.type }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                </div>

                <div class="row text-center">
                    <div class="actions" >
                        <input type="submit" value="confirm" name="proceed" class="checkout-button button alt wc-forward">
                    </div>
                </div>
            </form>
        </div>
    </div>


{% include "footer.html" %}

order/templates/orders.html
{% include "header.html" %}
{% load static %}
{% load mathfilters %}

    {% if cartitem is not None %}
    <div class="modal fade in" id="myModal" role="dialog">
        <div class="modal-dialog  modal-md  modal-dialog-centered">
          <div class="modal-content">
            <form action="/order/" method="post">
                {% csrf_token %}
            <div class="modal-body">
                <input name="cartitemid" value="{{ cartitem.id }}" hidden>
                <p>Feedback for product: {{ cartitem.itemid.productid.name }} | ORDER-00{{ cartitem.cartid.order_set.all.0.id }}</p>
                <hr>
                <div class="form-group">
                    <label>Star</label>
                    <div style="display: flex;">
                        <div class="rate">
                            <input type="radio" id="star5" name="rate" value="5" />
                            <label for="star5" title="text">5 stars</label>
                            <input type="radio" id="star4" name="rate" value="4" />
                            <label for="star4" title="text">4 stars</label>
                            <input type="radio" id="star3" name="rate" value="3" />
                            <label for="star3" title="text">3 stars</label>
                            <input type="radio" id="star2" name="rate" value="2" />
                            <label for="star2" title="text">2 stars</label>
                            <input type="radio" id="star1" name="rate" value="1" />
                            <label for="star1" title="text">1 star</label>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label>Content</label>
                    <textarea class="form-control" name="content" rows="5"></textarea>
                </div>
            </div>
            <div class="modal-footer">
                <div class="btn-group">
                    <button type="button" style="margin: 0px" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" name="process" value="feedback" style="margin: 0px" class="btn btn-primary">Submit</button>
                </div>
            </div>
            </form>
          </div>
        </div>
    </div>
    {% endif %}

    <div class="single-product-area">
            <h2 style="text-align: center; color: #5a88ca; font-weight:800;">ORDERED VIEW</h2>
            <br>
        <div class="zigzag-bottom"></div>
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <div class="white-box">
                        <div class="table-responsive">
                            <table class="table text-nowrap">
                                <thead>
                                    <tr class="row-listorder">
                                        <th>#</th>
                                        <th>Time</th>
                                        <th>State</th>
                                        <th class="text-center">Total</th>
                                        <th class="text-center">Shipment</th>
                                        <th class="text-center">Payment</th>

                                        <th colspan="2" class="text-center">Products</th>
                                        <th colspan="2" class="text-center"> Feedback </th>
                                        <th class="text-center"> Action </th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% for o in orders %}
                                    {% for ci in o.cartid.cartitem_set.all %}
                                    <tr >
                                        {% if forloop.counter == 1 %}
                                        <td rowspan="{{ o.cartid.cartitem_set.count }}">{{ o.id }}</td>
                                        <td rowspan="{{ o.cartid.cartitem_set.count }}">{{ o.time }}</td>
                                        <td class="text-center" rowspan="{{ o.cartid.cartitem_set.count }}" style="color: #ff6235;">{{ o.state }}</td>
                                        <td class="text-center" rowspan="{{ o.cartid.cartitem_set.count }}" >{{ o.num }}</td>
                                        <td class="text-center" rowspan="{{ o.cartid.cartitem_set.count }}" >{{ o.shipmentid.type }}</td>
                                        <td class="text-center" rowspan="{{ o.cartid.cartitem_set.count }}" >{{ o.paymentid.type }}</td>
                                        {% endif %}
                                        <td><img style="height: 70px" src="{{ ci.itemid.productid.img }}"></td>
                                        <td>- {{ ci.itemid.productid.name }}</td>
                                        {% if ci.feedback_set.all.count > 0 %}
                                        <td>{{ ci.feedback_set.all.0.content }}</td>
                                        <td>{{ ci.feedback_set.all.0.star }} ★</td>
                                        <td></td>
                                        {% else %}
                                        <td></td>
                                        <td></td>
                                        <td class="text-center" >
                                            <a class="btn btn-success" href="/order?feedback={{ ci.id }}" >Feedback</a>
                                        </td>
                                        {% endif %}

                                    </tr>
                                    {% endfor %}
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% include "footer.html" %}