cart/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('', views.index, name="index"),
    path('addtocartget', views.addtocartget, name="addtocart"),
    path('deletecartget', views.deletecartget, name="deletecartget"),
    path('docartitem', views.docartitem, name="docartitem")
]

e_commerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('product/', include('product.urls')),
    path('order/', include('order.urls')),
    path('cart/', include('cart.urls')),
    path('feedback/', include('feedback.urls')),

]

product/urls.py
from product import views
from django.urls import path
from . import views


urlpatterns =[
    path('', views.index, name = 'Home view' ),
    path('manageproduct', views.manageproduct, name="manageproduct"),
    path('deleteProduct/<int:id>', views.deleteProduct, name ='deleteProduct'),
    path('addProduct/', views.addProduct, name ='addProduct'),
    path('managecategory', views.managecategory, name="managecategory"),
    path('deleteCategory/<int:id>', views.deleteCategory, name='deleteCategory'),
    path('addCategory/', views.addCategory, name ='addCategory'),
    path('detail/<int:id>', views.productdetail, name = 'productdetail'),
    path('addcomment/', views.addcomment, name="addcomment"),
]

cart/models.py
from django.db import models
from user.models import User
from product.models import Item


class Cart(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    userid = models.ForeignKey(User, models.DO_NOTHING, db_column='UserID', blank=True,
                               null=True)  # Field name made lowercase.
    state = models.IntegerField(db_column='State', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        db_table = 'cart'

class CartItem(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    cartid = models.ForeignKey(Cart, models.DO_NOTHING, db_column='CartID')  # Field name made lowercase.
    itemid = models.ForeignKey(Item, models.DO_NOTHING, db_column='ItemID')  # Field name made lowercase.
    quantity = models.IntegerField(db_column='Quantity', blank=True, null=True)  # Field name made lowercase.
    cost = models.FloatField(db_column='Cost', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        db_table = 'cart_item'
        # unique_together = (('cartid', 'itemid'),)

feedback/models.py
from django.db import models
from user.models import User, Customer
from cart.models import CartItem

# Create your models here.
class Feedback(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    customeruserid = models.ForeignKey(Customer, models.DO_NOTHING, db_column='CustomerUserID')  # Field name made lowercase.
    cartitemid = models.ForeignKey(CartItem, models.DO_NOTHING, db_column='CartItemID')  # Field name made lowercase.
    content = models.CharField(db_column='Content', max_length=255, blank=True, null=True)  # Field name made lowercase.
    star = models.IntegerField(db_column='Star', blank=True, null=True)  # Field name made lowercase.
    time = models.DateField(db_column='Time', blank=True, null=True)  # Field name made lowercase.
    status = models.CharField(db_column='Status', max_length=255, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        db_table = 'feedback'

product/models.py
from datetime import datetime
from django.db import models
from user.models import User


class Item(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    productid = models.ForeignKey('Product', models.DO_NOTHING, db_column='ProductID')  # Field name made lowercase.
    outprice = models.FloatField(db_column='Outprice', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        db_table = 'item'


class Category(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    name = models.CharField(db_column='Name', max_length=255, blank=True, null=True)  # Field name made lowercase.
    categoryfather = models.IntegerField(db_column='CategoryFather', blank=True,
                                         null=True)  # Field name made lowercase.

    class Meta:
        db_table = 'category'


class Comment(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    userid = models.ForeignKey(User, models.DO_NOTHING, db_column='UserID', blank=True,
                               null=True)  # Field name made lowercase.
    itemid = models.ForeignKey('Item', models.DO_NOTHING, db_column='ItemID')  # Field name made lowercase.
    content = models.CharField(db_column='Content', max_length=255, blank=True, null=True)  # Field name made lowercase.
    time = models.DateField(db_column='Time', blank=True, null=True)  # Field name made lowercase.
    state = models.CharField(db_column='State', max_length=255, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        db_table = 'comment'

class Supplier(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    name = models.CharField(db_column='Name', max_length=255, blank=True, null=True)  # Field name made lowercase.
    phone = models.CharField(db_column='Phone', max_length=255, blank=True, null=True)  # Field name made lowercase.
    email = models.CharField(db_column='Email', max_length=255, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        db_table = 'supplier'


class Product(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    supplierid = models.ForeignKey('Supplier', models.DO_NOTHING, db_column='SupplierID')  # Field name made lowercase.
    categoryid = models.ForeignKey(Category, models.DO_NOTHING, db_column='CategoryID')  # Field name made lowercase.
    price = models.FloatField(db_column='Price', blank=True, null=True)  # Field name made lowercase.
    name = models.CharField(db_column='Name', max_length=255, blank=True, null=True)  # Field name made lowercase.
    quantity = models.IntegerField(db_column='Quantity', blank=True, null=True)  # Field name made lowercase.
    img = models.CharField(db_column='Img', max_length=255, blank=True, null=True)  # Field name made lowercase.
    desc = models.CharField(db_column='Desc', max_length=500, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        db_table = 'product'

user/models.py
from django.db import models


class User(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    username = models.CharField(db_column='Username', max_length=255, blank=True,
                                null=True)  # Field name made lowercase.
    password = models.CharField(db_column='Password', max_length=255, blank=True,
                                null=True)  # Field name made lowercase.
    birthday = models.CharField(db_column='Birthday', max_length=255)  # Field name made lowercase.
    sex = models.CharField(db_column='Sex', max_length=255, blank=True, null=True)  # Field name made lowercase.
    email = models.CharField(db_column='Email', max_length=255, blank=True, null=True)  # Field name made lowercase.
    phone = models.CharField(db_column='Phone', max_length=255, blank=True, null=True)  # Field name made lowercase.
    role = models.CharField(db_column='Role', max_length=255, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        db_table = 'user'


class Address(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    userid = models.ForeignKey('User', models.DO_NOTHING, db_column='UserID', blank=True,
                               null=True)  # Field name made lowercase.
    homenum = models.CharField(db_column='HomeNum', max_length=255, blank=True, null=True)  # Field name made lowercase.
    street = models.CharField(db_column='Street', max_length=255, blank=True, null=True)  # Field name made lowercase.
    district = models.CharField(db_column='District', max_length=255, blank=True,
                                null=True)  # Field name made lowercase.
    city = models.CharField(db_column='City', max_length=255, blank=True, null=True)  # Field name made lowercase.
    country = models.CharField(db_column='Country', max_length=255, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        db_table = 'address'


class Fullname(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    userid = models.ForeignKey('User', models.DO_NOTHING, db_column='UserID', blank=True,
                               null=True)  # Field name made lowercase.
    first = models.CharField(db_column='First', max_length=255, blank=True, null=True)  # Field name made lowercase.
    last = models.CharField(db_column='Last', max_length=255, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        db_table = 'fullname'

class Employee(models.Model):
    position = models.CharField(db_column='Position', max_length=255)  # Field name made lowercase.
    salary = models.FloatField(db_column='Salary', blank=True, null=True)  # Field name made lowercase.
    exp = models.IntegerField(db_column='Exp', blank=True, null=True)  # Field name made lowercase.
    userid = models.OneToOneField('User', models.DO_NOTHING, db_column='UserID', primary_key=True)  # Field name made lowercase.

    class Meta:
        db_table = 'employee'

class Customer(models.Model):
    type = models.CharField(db_column='Type', max_length=255)  # Field name made lowercase.
    userid = models.OneToOneField('User', models.DO_NOTHING, db_column='UserID', primary_key=True)  # Field name made lowercase.

    class Meta:
        db_table = 'customer'

class Logsearch(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    customeruserid = models.ForeignKey('Customer', models.DO_NOTHING, db_column='CustomerUserID')  # Field name made lowercase.
    time = models.DateField(db_column='Time')  # Field name made lowercase.
    content = models.CharField(db_column='Content', max_length=255)  # Field name made lowercase.

    class Meta:
        db_table = 'logsearch'


class Logviewdetail(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    customeruserid = models.ForeignKey('Customer', models.DO_NOTHING, db_column='CustomerUserID')  # Field name made lowercase.
    time = models.DateField(db_column='Time')  # Field name made lowercase.
    content = models.CharField(db_column='Content', max_length=255)  # Field name made lowercase.

    class Meta:
        db_table = 'logviewdetail'

product/templates/footer.html
{% load static %}
<div class="footer-top-area">
        <div class="zigzag-bottom"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-3 col-sm-6">
                    <div class="footer-about-us">
                        <h2><span>BoEC</span></h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Perferendis sunt id doloribus vero quam laborum quas alias dolores blanditiis iusto consequatur, modi aliquid eveniet eligendi iure eaque ipsam iste, pariatur omnis sint! Suscipit, debitis, quisquam. Laborum commodi veritatis magni at?</p>
                        <div class="footer-social">
                            <a href="#" target="_blank"><i class="fa fa-facebook"></i></a>
                            <a href="#" target="_blank"><i class="fa fa-twitter"></i></a>
                            <a href="#" target="_blank"><i class="fa fa-youtube"></i></a>
                            <a href="#" target="_blank"><i class="fa fa-linkedin"></i></a>
                        </div>
                    </div>
                </div>

                <div class="col-md-3 col-sm-6">
                    <div class="footer-menu">
                        <h2 class="footer-wid-title">User Navigation </h2>
                        <ul>
                            <li><a href="#">My account</a></li>
                            <li><a href="#">Order history</a></li>
                            <li><a href="#">Wishlist</a></li>
                            <li><a href="#">Vendor contact</a></li>
                            <li><a href="#">Front page</a></li>
                        </ul>
                    </div>
                </div>

                <div class="col-md-3 col-sm-6">
                    <div class="footer-menu">
                        <h2 class="footer-wid-title">Categories</h2>
                        <ul>
                            <li><a href="#">Mobile Phone</a></li>
                            <li><a href="#">Home accesseries</a></li>
                            <li><a href="#">LED TV</a></li>
                            <li><a href="#">Computer</a></li>
                            <li><a href="#">Gadets</a></li>
                        </ul>
                    </div>
                </div>

                <div class="col-md-3 col-sm-6">
                    <div class="footer-newsletter">
                        <h2 class="footer-wid-title">Newsletter</h2>
                        <p>Sign up to our newsletter and get exclusive deals you wont find anywhere else straight to your inbox!</p>
                        <div class="newsletter-form">
                            <form action="#">
                                <input type="email" placeholder="Type your email">
                                <input type="submit" value="Subscribe">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div> <!-- End footer top area -->

    <div class="footer-bottom-area">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <div class="copyright">
                        <p>&copy; @copyright E-Commerce PTIT 2021 <a href="http://www.freshdesignweb.com" target="_blank">Ha Thi Kim Phung</a></p>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="footer-card-icon">
                        <i class="fa fa-cc-discover"></i>
                        <i class="fa fa-cc-mastercard"></i>
                        <i class="fa fa-cc-paypal"></i>
                        <i class="fa fa-cc-visa"></i>
                    </div>
                </div>
            </div>
        </div>
    </div> <!-- End footer bottom area -->

    <!-- Latest jQuery form server -->
    <script src="https://code.jquery.com/jquery.min.js"></script>

    <!-- Bootstrap JS form CDN -->
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

    <!-- jQuery sticky menu -->
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/jquery.sticky.js' %}"></script>

    <!-- jQuery easing -->
    <script src="{% static 'js/jquery.easing.1.3.min.js' %}"></script>

    <!-- Main Script -->
    <script src="{% static 'js/main.js' %}"></script>

    <!-- Slider -->
    <script type="text/javascript" src="{% static 'js/bxslider.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/script.slider.js' %}"></script>

    {% if order is not None %}
    <script type="text/javascript">
        $(window).on('load', function() {
            $('#myModal').modal('show');
        });
    </script>
    {% endif %}

    {% if cartitem is not None %}
    <script type="text/javascript">
        $(window).on('load', function() {
            $('#myModal').modal('show');
        });
    </script>
    {% endif %}
  </body>
</html>

product/templates/productdetail.html
{% load static %}
{% load index %}
{% include "header.html" %}

    <div class="single-product-area">
        <div class="zigzag-bottom"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="product-content-right">
                        <div class="product-breadcroumb">
                            <a href="">Home</a>
                            <a href="">{{ category }}</a>
                            <a href="">{{ product.name }}</a>
                        </div>

                        <div class="row">
                            <div class="col-sm-6">
                                <div class="product-images">
                                    <div class="product-main-img">
                                        <img src="{{ product.img }}" alt="">
                                    </div>

                                </div>
                            </div>

                            <div class="col-sm-6">
                                <div class="product-inner">
                                    <h2 class="product-name">{{ product.name }}</h2>
                                    <div class="product-wid-rating">
                                        {% for i in 5|times %}
                                        {% if i|add:1 <= rate %}
                                        <i class="fa fa-star"></i>
                                        {% else %}
                                        <i class="fa fa-star" style="color: lightgray;"></i>
                                        {% endif %}
                                        {% endfor %}
                                    </div>
                                    <div class="product-inner-price">
                                        Price: <ins style="font-family:'Arial',sans-serif">{{ product.price }} đ</ins> <del style="font-size: xx-large;">{{ item.outprice }}</del>
                                    </div>
                                    <form method="post" action="/cart/docartitem" class="cart">
                                        {% csrf_token %}
                                        <input name="item" value="{{ item.id }}" hidden/>
                                        <div class="quantity">
                                            <input type="number" style="color: black" size="4" class="active" title="Qty" value="1" name="quantity" min="0" step="1">
                                        </div>
                                        <button type="submit" name="proceed" value="Detail">Add to cart</button>
                                    </form>


                                    <div class="product-inner-category">
                                        <p>Quantity: {{ product.quantity }} products </p>
                                    </div>

                                    <div class="product-inner-category">
                                        <p>Supplier: {{ product.supplierid.name }}  </p>
                                    </div>

                                    <div role="tabpanel">
                                        <ul class="product-tab" role="tablist">
                                                <li role="presentation"><a href="#home" aria-controls="desc" role="tab" data-toggle="tab">Description</a></li>

                                        </ul>
                                        <div class="tab-content">
                                            <div role="tabpanel" class="tab-pane fade in active" id="desc">
                                                <h2>Product Description</h2>
                                                <p>{{ product.desc }}</p>
                                            </div>

                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-12">
                                <div class="latest-product">
                                    <h2 class="section-title">Suggest Products</h2>
                                    <div class="product-carousel">
                                        {% for sgitem in items %}
                                        <div class="single-product">
                                            <div class="product-f-image">
                                                <img style="width:580px; height:300px;" src="{{ sgitem.productid.img }}" alt="">
                                                <div class="product-hover">
                                                    <a href="/cart/addtocartget?item={{ sgitem.id }}&before={{ item.id }}" class="add-to-cart-link"><i class="fa fa-shopping-cart"></i> Add to cart</a>
                                                    <a href="/product/detail/{{ sgitem.id }}" class="view-details-link"><i class="fa fa-link"></i> See details</a>
                                                </div>
                                            </div>

                                            <h2><a href="single-product.html">{{ sgitem.productid.name }}</a></h2>

                                            <div class="product-carousel-price">
                                                <ins style="font-family:'Arial',sans-serif">đ{{ sgitem.outprice }}</ins> <del style="font-family:'Arial',sans-serif">đ{{ sgitem.productid.price }}</del>
                                            </div>
                                        </div>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        </div>

<!--                     ADD   Comment-->
                        <div class="col-md-12">
                            <div class="product-body">
                                <div class="comment">
                                    <div class="product-tab">
                                        <ul class="tab-nav">

                                        </ul>
                                    </div>
                                </div>
                                <div class="user-comment">
                                    <form action="/product/addcomment/" class="submit-comment" method="post">
                                        {% csrf_token %}
                                        <input type="hidden" name="itemIDcomment" value="{{item.id}}">
                                        <textarea cols="50" rows="4" name="content" placeholder="Nhập bình luận về sản phẩm"></textarea>
                                        <button type="submit" name="add" class="btn btn-success">Add</button>
                                    </form>

                                </div>


                            </div>
                        </div> <!--comment-->


                            <!--View Comment -->
                        <div role="tabpanel">
                                        <ul class="product-tab" role="tablist">
                                            <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">Comments</a></li>
                                            <li role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">Feedback</a></li>
                                        </ul>
                                        <div class="tab-content">
                                            <div role="tabpanel" class="tab-pane fade in active" id="home">
                                                {% for comment in comments %}
                                                    <div class="comment mt-4 text-justify float-left">
                                                        <img src="https://i.imgur.com/yTFUilP.jpg" alt="" class="rounded-circle" width="40" height="40">
                                                        <h4>{{ comment.userid.fullname_set.all.0.first }} {{ comment.userid.fullname_set.all.0.last }}</h4> <span>- {{ comment.time }}</span> <br>
                                                        <p style="color: black">{{ comment.content }}</p>
                                                    </div>
                                                {%endfor %}
                                            </div>
                                            <div role="tabpanel" class="tab-pane fade" id="profile">
                                                {% for ci in item.cartitem_set.all %}
                                                {% for fb in ci.feedback_set.all %}
                                                    <div class="comment mt-4 text-justify float-left">
                                                        <img src="https://i.imgur.com/yTFUilP.jpg" alt="" class="rounded-circle" width="40" height="40">
                                                        <h4>{{ fb.customeruserid.userid.fullname_set.all.0.first }} {{ fb.customeruserid.userid.fullname_set.all.0.last }}</h4> {{ fb.star }} ★ <span> - {{ fb.time }}</span> <br>
                                                        <p style="color: black">{{ fb.content }}</p>
                                                    </div>
                                                {%endfor %}
                                                {%endfor %}
                                            </div>
                                        </div>
                                    </div>

                    </div>
                </div>
            </div>
        </div>
    </div>


{% include "footer.html" %}